### ISSUE TITLE
Doesn't work with a Cloudns

### ISSUE THREAD

**Issue by artiomn** [AnalogJ/lexicon#238]
https://github.com/AnalogJ/lexicon/blob/9197c8d9364fe18784d118f1440d6f09415a9785/lexicon/client.py#L14

Look at this pull request, please:
https://github.com/adferrand/docker-letsencrypt-dns/pull/17

**Comment by adferrand** [comment]
So what you are saying (yes, I contribute also a little on lexicon) is that your pr I merged for my Docker allows to circumvent a limitation on lexicon for cloudns, right?

If I understand well, standard processing in lexicon is to strip down the subdomain from domain given as parameter to lexicon. That is because most of APIs wait for the top level domain and act on it to manipulate subdomains. But for ClouDNS, it waits for the subdomain itself.

If I am correct, then we should expose the original domain given as parameter in the config array to the providers, then correct the ClouDNS provider to use it instead of "domain" key to construct the URL.

**Comment by adferrand** [comment]
Or for your case it is because you delegated the subdomain gestion to an independent secondary zone, so in fact your "domain" should be really the complete given parameter including the subdomain, because it is indeed related to the secondary zone where the modification should be done.

In this case, the limitation is not restricted to ClouDNS, but apply to any provider. Then we need an option on lexicon to include all parts of the given domain when required.

**Comment by adferrand** [comment]
... Which seems to be the purpose of the delegated option. It seems to be used when a subdomain gestion is delegated by the main domain to a secondary zone.

If you put the subdomain part in delegated option, it seems from the code that the "domain" key in options will contain the subdomain part.

Could you test that ? 

For my concern, LEXICON_OPTIONS stays really necessary for delegated domains, and I will add this in the documentation to picture usage of LEXICON_OPTIONS.

**Comment by artiomn** [comment]
Yes, it works, with the settings, like this:
```
  letsencrypt-dns:
    #build: ./leapp
    image: adferrand/letsencrypt-dns
    volumes:
      - ./certs/letsencrypt:/etc/letsencrypt
    environment:
      - "LETSENCRYPT_USER_MAIL=mail@gmail.com"
      - "LEXICON_PROVIDER=cloudns"
      - "LEXICON_PROVIDER_OPTIONS=--auth-id=777 --auth-password=PASSWORD --delegated=MY_ZONE.cloudns.cc"
```
